version: '3.8'

services:
  cms:
    build:
      context: .
      args:
        VITE_APP_BASE_API_URL: ${VITE_APP_BASE_API_URL}
        VITE_APP_FIRE_BASE_CONFIG: ${VITE_APP_FIRE_BASE_CONFIG}
    image: shirleys-food-cms:latest
    container_name: shirleys-food-cms-production
    ports:
      - '127.0.0.1:4001:3000'
    restart: unless-stopped
