version: '3.8'

services:
  cms:
    build: .
    image: shirleys-food-cms:latest
    container_name: shirleys-food-cms-production
    ports:
      - '127.0.0.1:4001:3000'
    env_file:
      - ../../.env
    restart: unless-stopped
